// layout.js
import Footer from './components/Footer/Footer';  
import Header from './components/Header/Header';  
import { UserProvider } from './Context/UserContext'; // Asegúrate de importar el contexto
import './globals.css';  

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Header /> 
          <main>{children}</main>  
          <Footer />  
        </UserProvider>
      </body>
    </html>
  );
}
